kind: pipeline
name: default

steps:
  - name: package
    image: maven:3.6.1-jdk-8-slim
    commands:
      - mvn package
  - name: build
    image: docker
    commands:
      - docker rm $${HOST_NAME} -f || true
      - docker build -t $${DOCKER_REPO_NAME} .
    environment:
      DOCKER_REPO_NAME:
        from_secret: DOCKER_REPO_NAME
      HOST_NAME:
        from_secret: HOST_NAME
    volumes:
      - name: socket
        path: /var/run/docker.sock
  - name: run
    image: docker
    commands:
      - docker run
        --detach
        --restart=always
        --name $${HOST_NAME}
        --network="nginx_default"
        -e "VIRTUAL_HOST=$${HOST_NAME}.$${DOMAIN}"
        -e "LETSENCRYPT_HOST=$${HOST_NAME}.$${DOMAIN}"
        -e "LETSENCRYPT_EMAIL=$${EMAIL}"
        $${DOCKER_REPO_NAME}
    environment:
      DOCKER_REPO_NAME:
        from_secret: DOCKER_REPO_NAME
      HOST_NAME:
        from_secret: HOST_NAME
      EMAIL:
        from_secret: EMAIL
      DOMAIN:
        from_secret: DOMAIN
    volumes:
      - name: socket
        path: /var/run/docker.sock
  - name: notify
    image: drillster/drone-email
    environment:
      PLUGIN_HOST:
        from_secret: MAILGUN_SMTP_HOST
      PLUGIN_FROM:
        from_secret: MAILGUN_SMTP_SENDER
      PLUGIN_RECIPIENTS:
        from_secret: EMAIL
      PLUGIN_USERNAME:
        from_secret: MAILGUN_SMTP_USERNAME
      PLUGIN_PASSWORD:
        from_secret: MAILGUN_SMTP_PASSWORD
      PLUGIN_RECIPIENTS_ONLY: true
volumes:
  - name: socket
    host:
      path: /var/run/docker.sock

---
kind: secret
name: DOMAIN
get:
  path: secret/drone-ci
  name: DOMAIN

---
kind: secret
name: EMAIL
get:
  path: secret/drone-ci
  name: EMAIL

---
kind: secret
name: NEXUS_NPM_REPO
get:
  path: secret/drone-ci
  name: NEXUS_NPM_REPO

---
kind: secret
name: NPM_TOKEN
get:
  path: secret/drone-ci
  name: NPM_TOKEN

---
kind: secret
name: MAILGUN_SMTP_PASSWORD
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_PASSWORD

---
kind: secret
name: MAILGUN_SMTP_HOST
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_HOST

---
kind: secret
name: MAILGUN_SMTP_USERNAME
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_USERNAME

---
kind: secret
name: MAILGUN_SMTP_SENDER
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_SENDER
